name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Install azure-cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - uses: actions/checkout@v2

      - uses: ./action-a
        with:
          MY_NAME: "Mona"